# Generated by Django 3.0.5 on 2020-05-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('course', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
    ]
