# Generated by Django 3.0.5 on 2020-05-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200504_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
