# Generated by Django 3.0.5 on 2020-05-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=20)),
                ('items', models.ManyToManyField(to='listings.listing')),
            ],
        ),
    ]
